exports.queryList = {
    GET_STORE_LIST_QUERY:'SELECT STORE_ID, STORE_NAME, STORE_CODE FROM BMS.STORE',
    SAVE_STORE_QUERY:'INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, ADDRESS) VALUES(?, ?, ?, ?, ?)',
}
