exports.queryList = {
    GET_STORE_LIST_QUERY:'SELECT STORE_ID, STORE_NAME, STORE_CODE FROM BMS.STORE',
    SAVE_STORE_QUERY : 'INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, ADDRESS , CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5)',
    GET_BOOK_LIST_QUERY :'SELECT BOOK_ID, BOOK_TITLE, BOOK_AUTHER, BOOK_PUBLISHER FROM BMS.BOOK',
}
