exports.queryList = {
    GET_STORE_LIST_QUERY:'SELECT STORE_ID, STORE_NAME, STORE_CODE FROM BMS.STORE',
    SAVE_STORE_QUERY:'INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, ADDRESS) VALUES($1,$2, $3, $4, $5)',
}
